version: '3.9'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: ebikestore
    ports:
      - '3306:3306'
    volumes:
      - dbdata:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --sql_mode=""
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: example
      MYSQL_DATABASE: ebikestore
      APP_PORT: 3001
      APP_ORIGIN: http://localhost:3000
    ports:
      - '3001:3001'
    depends_on:
      - db
volumes:
  dbdata:

